// V7 visual calibration: preserve quiz behavior, only refine layout/typography.
const NLM_SYSTEM_FONT = '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif';

const baseThemeCssV7 = themeCss;
themeCss = function(theme) {
  const p = THEMES[theme] || THEMES['nlm-dark'];
  const font = theme === 'paper' ? p.font : NLM_SYSTEM_FONT;
  return `
    :root{color-scheme:${p.scheme};--nlm-bg:${p.bg};--nlm-panel:${p.panel};--nlm-option:${p.option};--nlm-option-hover:${p.optionHover};--nlm-text:${p.text};--nlm-muted:${p.muted};--nlm-line:${p.line};--nlm-line-soft:${p.lineSoft};--nlm-green:${p.green};--nlm-green-text:${p.greenText};--nlm-green-bg:${p.greenBg};--nlm-red:${p.red};--nlm-red-text:${p.redText};--nlm-red-bg:${p.redBg};--nlm-accent:${p.accent};--nlm-btn:${p.btn};--nlm-btn-text:${p.btnText};--nlm-drawer:${p.drawer};--nlm-hint:${p.hint};--nlm-font:${font}}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0!important;min-height:100vh!important;padding:20px!important;background:var(--nlm-bg)!important;color:var(--nlm-text)!important;font-family:var(--nlm-font)!important}
    .container{max-width:700px!important;margin:0 auto!important;padding:0!important}
    .header{display:block!important;text-align:center!important;color:var(--nlm-text)!important;padding:30px 20px 18px!important;background:transparent!important;border:0!important;box-shadow:none!important}
    .header h1{font-size:28px!important;font-weight:700!important;line-height:1.2!important;letter-spacing:-.015em!important;margin:0 0 8px!important;color:var(--nlm-text)!important;text-shadow:none!important}
    .header .meta{font-size:14px!important;line-height:1.4!important;color:var(--nlm-muted)!important;opacity:1!important}
    .progress-bar{height:8px!important;margin:20px 0 0!important;overflow:hidden!important;border-radius:10px!important;background:var(--nlm-line)!important}
    .progress-fill{height:100%!important;width:0!important;border-radius:10px!important;background:var(--nlm-accent)!important;transition:width .35s ease!important}
    #quiz-container{width:100%!important;margin:0 auto!important;padding:18px 0 92px!important}
    .question{display:none!important;background:var(--nlm-panel)!important;border:1px solid var(--nlm-line-soft)!important;border-radius:16px!important;box-shadow:0 10px 40px rgba(0,0,0,.15)!important;padding:30px!important;color:var(--nlm-text)!important}.question.active{display:block!important}
    .q-header{display:flex!important;justify-content:flex-end!important;align-items:center!important;margin-bottom:20px!important;font-size:13px!important;color:var(--nlm-muted)!important}.q-number{font-weight:600!important;color:var(--nlm-accent)!important}.q-of{display:none!important}
    .q-text{font-size:18px!important;font-weight:600!important;line-height:1.5!important;letter-spacing:0!important;color:var(--nlm-text)!important;margin:0 0 25px!important}
    .hint-box{margin:12px 0!important;border-radius:10px!important;overflow:hidden!important;background:var(--nlm-hint)!important;border:1px solid var(--nlm-line)!important}.hint-toggle{width:100%!important;padding:10px 16px!important;background:transparent!important;border:0!important;cursor:pointer!important;font-size:14px!important;font-weight:600!important;color:var(--nlm-muted)!important;text-align:left!important}.hint-toggle:hover{background:var(--nlm-option-hover)!important}.hint-content{padding:0 16px!important;max-height:0!important;overflow:hidden!important;transition:max-height .3s,padding .3s!important;font-size:14px!important;color:var(--nlm-muted)!important;line-height:1.5!important}.hint-box.show .hint-content{padding:0 16px 12px!important;max-height:240px!important}
    .options{display:flex!important;flex-direction:column!important;gap:12px!important}.option-wrapper{display:flex!important;flex-direction:column!important}
    .option{position:relative!important;display:flex!important;align-items:flex-start!important;gap:14px!important;width:100%!important;padding:16px 18px!important;border:2px solid var(--nlm-line)!important;border-radius:12px!important;background:var(--nlm-option)!important;color:var(--nlm-text)!important;cursor:pointer!important;text-align:left!important;transition:border-color .2s,background .2s!important;font-size:15px!important;line-height:1.5!important}
    .option:hover:not(.disabled){border-color:var(--nlm-accent)!important;background:var(--nlm-option-hover)!important}.option.disabled{cursor:default!important}.opt-label{display:flex!important;align-items:center!important;justify-content:center!important;width:32px!important;height:32px!important;border-radius:50%!important;background:var(--nlm-line)!important;color:var(--nlm-text)!important;font-weight:700!important;font-size:14px!important;flex-shrink:0!important}.opt-text{padding-top:5px!important;color:inherit!important;line-height:1.5!important}
    .option.selected.correct,.option.show-correct{border-color:var(--nlm-green)!important;background:var(--nlm-green-bg)!important}.option.selected.incorrect{border-color:var(--nlm-red)!important;background:var(--nlm-red-bg)!important}.option.selected.correct .opt-label,.option.show-correct .opt-label{background:var(--nlm-green)!important;color:#fff!important}.option.selected.incorrect .opt-label{background:var(--nlm-red)!important;color:#fff!important}
    .option-feedback{display:none!important}.nlm-inline-feedback{margin:8px 0 4px 46px!important;padding:0 16px 10px 0!important;color:var(--nlm-text)!important;font-size:14px!important;line-height:1.5!important}.nlm-feedback-status{display:flex!important;align-items:center!important;gap:6px!important;font-weight:600!important;margin-bottom:4px!important}.nlm-feedback-status.correct{color:var(--nlm-green-text)!important}.nlm-feedback-status.incorrect{color:var(--nlm-red-text)!important}.nlm-feedback-icon{font-size:15px!important;line-height:1!important}.nlm-rationale{color:var(--nlm-text)!important}.nlm-inline-feedback.neutral{opacity:.84!important}.nlm-inline-feedback.neutral .nlm-rationale{color:var(--nlm-muted)!important}
    .next-btn{display:none!important}.results{display:none!important}
    .nlm-topbar{position:fixed!important;z-index:1000!important;top:14px!important;left:0!important;right:0!important;height:auto!important;background:transparent!important;pointer-events:none!important}.nlm-topbar-inner{width:min(700px,calc(100% - 40px))!important;margin:0 auto!important;display:flex!important;justify-content:flex-end!important;align-items:center!important;padding:0!important;pointer-events:auto!important}.nlm-counter{position:absolute!important;width:1px!important;height:1px!important;opacity:0!important;pointer-events:none!important;overflow:hidden!important}.nlm-top-actions{display:flex!important;align-items:center!important;gap:4px!important;background:var(--nlm-panel)!important;border:1px solid var(--nlm-line)!important;border-radius:999px!important;padding:4px 7px!important;box-shadow:0 4px 18px rgba(0,0,0,.08)!important}.nlm-kebab,.nlm-review-link,.nlm-restart-link{appearance:none!important;border:0!important;background:transparent!important;color:var(--nlm-muted)!important;cursor:pointer!important;padding:6px 8px!important;font-family:var(--nlm-font)!important;font-size:12px!important}.nlm-kebab{font-size:21px!important;line-height:1!important}.nlm-kebab:hover,.nlm-review-link:hover,.nlm-restart-link:hover{color:var(--nlm-text)!important}
    .nlm-footer-nav{position:fixed!important;z-index:900!important;left:0!important;right:0!important;bottom:0!important;background:linear-gradient(to top,var(--nlm-bg) 68%,transparent)!important;pointer-events:none!important}.nlm-footer-inner{width:min(700px,calc(100% - 40px))!important;margin:0 auto!important;padding:24px 0 16px!important;display:flex!important;align-items:center!important;justify-content:flex-end!important;gap:8px!important;pointer-events:auto!important}.nlm-nav-btn{appearance:none!important;border:1px solid var(--nlm-line)!important;background:var(--nlm-panel)!important;color:var(--nlm-text)!important;border-radius:10px!important;padding:10px 16px!important;font-size:13px!important;font-weight:600!important;cursor:pointer!important;box-shadow:0 4px 16px rgba(0,0,0,.08)!important}.nlm-nav-btn.primary{background:var(--nlm-btn)!important;color:var(--nlm-btn-text)!important;border-color:var(--nlm-btn)!important}.nlm-nav-btn:disabled{opacity:.35!important;cursor:not-allowed!important}
    .nlm-drawer-backdrop{position:fixed!important;inset:0!important;z-index:1200!important;background:#0007!important;display:none!important}.nlm-drawer-backdrop.open{display:block!important}.nlm-drawer{position:absolute!important;top:0!important;right:0!important;width:min(390px,92vw)!important;height:100%!important;overflow:auto!important;background:var(--nlm-drawer)!important;border-left:1px solid var(--nlm-line)!important;padding:24px!important}.nlm-drawer-head{display:flex!important;align-items:center!important;justify-content:space-between!important;margin-bottom:20px!important}.nlm-drawer-head strong{font-size:15px!important}.nlm-close{border:0!important;background:transparent!important;color:var(--nlm-muted)!important;font-size:24px!important;cursor:pointer!important}.nlm-question-grid{display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:8px!important}.nlm-qjump{height:42px!important;border-radius:10px!important;border:1px solid var(--nlm-line)!important;background:var(--nlm-option)!important;color:var(--nlm-muted)!important;cursor:pointer!important}.nlm-qjump.current{outline:2px solid var(--nlm-accent)!important;outline-offset:1px!important;color:var(--nlm-text)!important}.nlm-qjump.correct{border-color:var(--nlm-green)!important;color:var(--nlm-green-text)!important}.nlm-qjump.wrong{border-color:var(--nlm-red)!important;color:var(--nlm-red-text)!important}.nlm-legend{display:flex!important;gap:12px!important;flex-wrap:wrap!important;margin-top:16px!important;color:var(--nlm-muted)!important;font-size:11px!important}.nlm-dot{width:8px!important;height:8px!important;border-radius:50%!important;display:inline-block!important;margin-right:4px!important}.nlm-dot.green{background:var(--nlm-green)!important}.nlm-dot.red{background:var(--nlm-red)!important}
    .nlm-results{width:min(700px,calc(100% - 40px))!important;margin:0 auto!important;padding:82px 0 78px!important}.nlm-result-hero{text-align:center!important;background:var(--nlm-panel)!important;border:1px solid var(--nlm-line-soft)!important;border-radius:16px!important;padding:30px!important;box-shadow:0 10px 40px rgba(0,0,0,.15)!important}.nlm-result-hero small{color:var(--nlm-muted)!important}.nlm-score{font-size:56px!important;font-weight:700!important;letter-spacing:-.04em!important;margin:14px 0 4px!important}.nlm-result-summary{color:var(--nlm-muted)!important;font-size:15px!important}.nlm-result-actions{display:flex!important;justify-content:center!important;gap:8px!important;flex-wrap:wrap!important;margin-top:20px!important}.nlm-result-section{margin-top:18px!important}.nlm-result-section h3{font-size:15px!important;margin:0 0 12px!important}.nlm-mistakes{display:grid!important;gap:10px!important}.nlm-mistake{border:1px solid var(--nlm-line)!important;border-radius:14px!important;background:var(--nlm-panel)!important;padding:17px!important;box-shadow:0 6px 24px rgba(0,0,0,.08)!important}.nlm-mistake-top{display:flex!important;align-items:start!important;justify-content:space-between!important;gap:12px!important}.nlm-mistake-number{color:var(--nlm-red-text)!important;font-size:11px!important;font-weight:750!important}.nlm-mistake-question{font-weight:650!important;line-height:1.45!important;margin-top:5px!important}.nlm-answer-row{margin-top:12px!important;font-size:13px!important;line-height:1.5!important}.nlm-answer-row b{display:block!important;color:var(--nlm-muted)!important;font-size:10px!important;text-transform:uppercase!important;letter-spacing:.06em!important;margin-bottom:3px!important}.nlm-answer-row.wrong{color:var(--nlm-red-text)!important}.nlm-answer-row.correct{color:var(--nlm-green-text)!important}.nlm-review-q{margin-top:12px!important;border:0!important;background:transparent!important;color:var(--nlm-accent)!important;font-weight:650!important;cursor:pointer!important;padding:0!important;font-size:12px!important}.nlm-perfect{border:1px solid var(--nlm-green)!important;background:var(--nlm-green-bg)!important;padding:18px!important;border-radius:14px!important;color:var(--nlm-green-text)!important;line-height:1.5!important}
    .nlm-print-sheet{display:none}
    @media print{@page{size:A4;margin:14mm}body>*:not(.nlm-print-sheet){display:none!important}.nlm-print-sheet{display:block!important;color:#111!important;background:#fff!important;font-family:Arial,"Helvetica Neue",sans-serif!important}.nlm-print-sheet h1{font-size:22pt;margin:0 0 4mm}.nlm-print-meta{margin:0 0 8mm;color:#555;font-size:10pt}.nlm-print-card{break-inside:avoid-page;border:1px solid #d6d6d6;border-radius:10px;padding:6mm;margin:0 0 6mm}.nlm-print-number{font-size:8pt;font-weight:700;letter-spacing:.08em;color:#777}.nlm-print-card h2{font-size:13pt;line-height:1.4;margin:2mm 0 5mm}.nlm-print-row{margin:3mm 0;font-size:10pt;line-height:1.45}.nlm-print-row b{display:block;font-size:7.5pt;text-transform:uppercase;letter-spacing:.06em;color:#666;margin-bottom:1mm}.nlm-print-row.wrong span,.nlm-print-row.wrong-note span{color:#a5222e}.nlm-print-row.correct span{color:#126d37}.nlm-repair-prompt{margin-top:5mm;padding:3mm 4mm;background:#f4f4f4;border-left:3px solid #444;font-size:9pt;line-height:1.45}}
    @media(max-width:600px){body{padding:12px!important}.header{padding:58px 6px 12px!important}.header h1{font-size:22px!important}.header .meta{font-size:13px!important}.progress-bar{margin-top:14px!important}#quiz-container{padding:12px 0 86px!important}.question{padding:20px 16px!important;border-radius:14px!important}.q-header{margin-bottom:16px!important}.q-text{font-size:17px!important;margin-bottom:20px!important}.option{padding:14px 13px!important;gap:11px!important;font-size:14px!important}.opt-label{width:30px!important;height:30px!important;font-size:13px!important}.nlm-inline-feedback{margin-left:41px!important;font-size:13px!important}.nlm-topbar{top:8px!important}.nlm-topbar-inner,.nlm-footer-inner,.nlm-results{width:calc(100% - 24px)!important}.nlm-review-link{display:none!important}.nlm-question-grid{grid-template-columns:repeat(4,1fr)!important}}
  `;
};

const baseEnhancerScriptV7 = enhancerScript;
enhancerScript = function() {
  return baseEnhancerScriptV7()
    .replace(
      "const grid = backdrop.querySelector('.nlm-question-grid');",
      "const grid = backdrop.querySelector('.nlm-question-grid');\\n    const progressFill = document.querySelector('.progress-fill');\\n    const headerMeta = document.querySelector('.header .meta');\\n    if (headerMeta) headerMeta.textContent = total + ' question' + (total === 1 ? '' : 's');"
    )
    .replace(
      "counter.textContent = (current + 1) + '/' + total;",
      "counter.textContent = (current + 1) + '/' + total;\\n      const currentNumber = questions[current]?.querySelector('.q-number');\\n      if (currentNumber) currentNumber.textContent = (current + 1) + '/' + total;\\n      if (progressFill) progressFill.style.width = (((current + 1) / Math.max(total, 1)) * 100).toFixed(2) + '%';"
    )
    .replace(
      "const correctCount = state.filter(s => s.correct === true).length;",
      "if (progressFill) progressFill.style.width = '100%';\\n      const correctCount = state.filter(s => s.correct === true).length;"
    );
};
