const THEMES = {
  'nlm-dark': {
    scheme:'dark', bg:'#202428', panel:'#202428', option:'#181c20', optionHover:'#1c2126', text:'#f5f6f7', muted:'#a4a7ab', subtle:'#848a91', line:'#2d3339', lineSoft:'#292e34', green:'#17c964', greenText:'#52e58a', greenBg:'#15231b', red:'#f05b67', redText:'#ff858f', redBg:'#2a181b', accent:'#a9c7ff', btn:'#e5e7eb', btnText:'#202428', drawer:'#191d21', hint:'#272c31', font:'Arial,"Helvetica Neue",sans-serif'
  },
  'nlm-light': {
    scheme:'light', bg:'#f5f6f7', panel:'#ffffff', option:'#f0f1f2', optionHover:'#eaedef', text:'#22262b', muted:'#6f747b', subtle:'#8a9098', line:'#d7dadd', lineSoft:'#e4e6e8', green:'#159b50', greenText:'#08783a', greenBg:'#e9f7ef', red:'#d84c58', redText:'#b12f3a', redBg:'#fdecee', accent:'#416da8', btn:'#262a2f', btnText:'#ffffff', drawer:'#ffffff', hint:'#eceff1', font:'Arial,"Helvetica Neue",sans-serif'
  },
  focus: {
    scheme:'light', bg:'#f3f4f7', panel:'#ffffff', option:'#fafbfc', optionHover:'#f4f5f8', text:'#171b24', muted:'#7e8796', subtle:'#9299a6', line:'#e1e4ea', lineSoft:'#eceef2', green:'#2e9b5f', greenText:'#257b4d', greenBg:'#ecf8f1', red:'#c9505e', redText:'#a83c48', redBg:'#fff0f2', accent:'#5868d8', btn:'#1d2230', btnText:'#ffffff', drawer:'#ffffff', hint:'#f6f2ff', font:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif'
  },
  midnight: {
    scheme:'dark', bg:'#090b11', panel:'#0f131b', option:'#141923', optionHover:'#1a202c', text:'#f4f5fb', muted:'#8e97aa', subtle:'#70798c', line:'#272e3a', lineSoft:'#202631', green:'#43b977', greenText:'#66d998', greenBg:'#12231a', red:'#d75c69', redText:'#f07a85', redBg:'#29171b', accent:'#8d9aff', btn:'#8d9aff', btnText:'#0a0c12', drawer:'#0d1118', hint:'#171d2a', font:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif'
  },
  paper: {
    scheme:'light', bg:'#eee7da', panel:'#fffaf0', option:'#fdf6e9', optionHover:'#f7eddd', text:'#382f25', muted:'#8b7b6a', subtle:'#a09280', line:'#d9cbb6', lineSoft:'#eadfcd', green:'#6f9658', greenText:'#5f7f4d', greenBg:'#edf4e6', red:'#b86a5f', redText:'#985348', redBg:'#fae8e1', accent:'#9a6b3b', btn:'#4b3b2c', btnText:'#fffaf0', drawer:'#fffaf0', hint:'#f8edcf', font:'Georgia,"Times New Roman",serif'
  },
  mint: {
    scheme:'light', bg:'#edf8f4', panel:'#fbfffd', option:'#f5fbf8', optionHover:'#edf7f2', text:'#15372e', muted:'#6d8f84', subtle:'#87a69c', line:'#d0e5dd', lineSoft:'#e1efe9', green:'#2d9b64', greenText:'#237a50', greenBg:'#e5f6ed', red:'#d26562', redText:'#ad4c49', redBg:'#fff0ef', accent:'#17896b', btn:'#17483a', btnText:'#ffffff', drawer:'#fbfffd', hint:'#fff9e8', font:'Inter,ui-sans-serif,system-ui,-apple-system,"Segoe UI",sans-serif'
  }
};

function themeCss(theme) {
  const p = THEMES[theme] || THEMES['nlm-dark'];
  return `
    :root{color-scheme:${p.scheme};--nlm-bg:${p.bg};--nlm-panel:${p.panel};--nlm-option:${p.option};--nlm-option-hover:${p.optionHover};--nlm-text:${p.text};--nlm-muted:${p.muted};--nlm-subtle:${p.subtle};--nlm-line:${p.line};--nlm-line-soft:${p.lineSoft};--nlm-green:${p.green};--nlm-green-text:${p.greenText};--nlm-green-bg:${p.greenBg};--nlm-red:${p.red};--nlm-red-text:${p.redText};--nlm-red-bg:${p.redBg};--nlm-accent:${p.accent};--nlm-btn:${p.btn};--nlm-btn-text:${p.btnText};--nlm-drawer:${p.drawer};--nlm-hint:${p.hint};--nlm-font:${p.font}}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0!important;min-height:100vh!important;padding:0!important;background:var(--nlm-bg)!important;color:var(--nlm-text)!important;font-family:var(--nlm-font)!important}
    .container{max-width:none!important;margin:0!important;padding:0!important}.header{display:none!important}
    #quiz-container{width:min(760px,calc(100% - 32px));margin:0 auto;padding:86px 0 110px!important}
    .question{display:none!important;background:transparent!important;border:0!important;border-radius:0!important;box-shadow:none!important;padding:0!important;color:var(--nlm-text)!important}.question.active{display:block!important}
    .q-header{display:none!important}.q-text{font-size:19px!important;font-weight:650!important;line-height:1.48!important;letter-spacing:-.01em!important;color:var(--nlm-text)!important;margin:0 14px 38px!important}
    .hint-box{margin:0 0 12px!important;border-radius:15px!important;overflow:hidden!important;background:var(--nlm-hint)!important;border:1px solid var(--nlm-line)!important}.hint-toggle{padding:11px 15px!important;color:var(--nlm-muted)!important;font-size:13px!important}.hint-toggle:hover{background:transparent!important}.hint-content{color:var(--nlm-muted)!important;font-size:13px!important;line-height:1.55!important}.hint-box.show .hint-content{padding:0 15px 13px!important}
    .options{display:flex!important;flex-direction:column!important;gap:10px!important}.option-wrapper{display:block!important}
    .option{position:relative!important;display:grid!important;grid-template-columns:34px minmax(0,1fr)!important;align-items:start!important;gap:10px!important;width:100%!important;padding:20px 22px!important;border-radius:15px!important;border:1px solid transparent!important;background:var(--nlm-option)!important;color:var(--nlm-text)!important;cursor:pointer!important;text-align:left!important;transition:border-color .15s,background .15s!important;font-size:16px!important;line-height:1.55!important}
    .option:hover:not(.disabled){background:var(--nlm-option-hover)!important;border-color:var(--nlm-line)!important}.option.disabled{cursor:default!important}.opt-label{width:28px!important;height:28px!important;border-radius:50%!important;background:transparent!important;display:grid!important;place-items:center!important;color:var(--nlm-muted)!important;font-weight:500!important;font-size:16px!important;flex:none!important}.opt-text{padding:1px 0 0!important;color:inherit!important}
    .option.selected.correct,.option.show-correct{border:2px solid var(--nlm-green)!important;background:var(--nlm-option)!important}.option.selected.incorrect{border:2px solid var(--nlm-red)!important;background:var(--nlm-option)!important}.option.selected.correct .opt-label,.option.show-correct .opt-label,.option.selected.incorrect .opt-label{background:transparent!important;color:var(--nlm-text)!important}
    .option-feedback{display:none!important}.nlm-inline-feedback{grid-column:2;margin-top:12px;padding-top:0;color:var(--nlm-text);font-size:15px;line-height:1.55}.nlm-feedback-status{display:flex;align-items:center;gap:9px;font-weight:750;margin-bottom:10px}.nlm-feedback-status.correct{color:var(--nlm-green-text)}.nlm-feedback-status.incorrect{color:var(--nlm-red-text)}.nlm-feedback-icon{font-size:19px;line-height:1}.nlm-rationale{color:var(--nlm-text)}
    .next-btn{display:none!important}.results{display:none!important}
    .nlm-topbar{position:fixed;z-index:1000;top:0;left:0;right:0;height:72px;background:linear-gradient(to bottom,var(--nlm-bg) 65%,transparent);pointer-events:none}.nlm-topbar-inner{height:58px;width:min(830px,calc(100% - 24px));margin:0 auto;display:flex;align-items:center;justify-content:space-between;padding:0 13px;pointer-events:auto}.nlm-counter{appearance:none;border:0;background:transparent;color:var(--nlm-muted);font-size:16px;padding:8px 2px;cursor:pointer}.nlm-kebab{appearance:none;border:0;background:transparent;color:var(--nlm-muted);font-size:26px;padding:2px 8px;cursor:pointer;line-height:1}.nlm-top-actions{display:flex;align-items:center;gap:4px}.nlm-review-link{appearance:none;border:0;background:transparent;color:var(--nlm-muted);font-size:12px;cursor:pointer;padding:7px 8px}.nlm-review-link:hover,.nlm-counter:hover{color:var(--nlm-text)}
    .nlm-footer-nav{position:fixed;z-index:900;left:0;right:0;bottom:0;background:linear-gradient(to top,var(--nlm-bg) 70%,transparent);pointer-events:none}.nlm-footer-inner{width:min(760px,calc(100% - 32px));margin:0 auto;padding:28px 0 18px;display:flex;align-items:center;justify-content:flex-end;gap:8px;pointer-events:auto}.nlm-nav-btn{appearance:none;border:1px solid var(--nlm-line);background:var(--nlm-option);color:var(--nlm-text);border-radius:999px;padding:10px 17px;font-size:13px;font-weight:650;cursor:pointer}.nlm-nav-btn.primary{background:var(--nlm-btn);color:var(--nlm-btn-text);border-color:var(--nlm-btn)}.nlm-nav-btn:disabled{opacity:.3;cursor:not-allowed}
    .nlm-drawer-backdrop{position:fixed;inset:0;z-index:1200;background:#0008;display:none}.nlm-drawer-backdrop.open{display:block}.nlm-drawer{position:absolute;top:0;right:0;width:min(390px,92vw);height:100%;overflow:auto;background:var(--nlm-drawer);border-left:1px solid var(--nlm-line);padding:24px}.nlm-drawer-head{display:flex;align-items:center;justify-content:space-between;margin-bottom:20px}.nlm-drawer-head strong{font-size:15px}.nlm-close{border:0;background:transparent;color:var(--nlm-muted);font-size:24px;cursor:pointer}.nlm-question-grid{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.nlm-qjump{height:42px;border-radius:10px;border:1px solid var(--nlm-line);background:var(--nlm-option);color:var(--nlm-muted);cursor:pointer}.nlm-qjump.current{outline:2px solid var(--nlm-accent);outline-offset:1px;color:var(--nlm-text)}.nlm-qjump.correct{border-color:var(--nlm-green);color:var(--nlm-green-text)}.nlm-qjump.wrong{border-color:var(--nlm-red);color:var(--nlm-red-text)}.nlm-legend{display:flex;gap:12px;flex-wrap:wrap;margin-top:16px;color:var(--nlm-muted);font-size:11px}.nlm-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:4px}.nlm-dot.green{background:var(--nlm-green)}.nlm-dot.red{background:var(--nlm-red)}
    .nlm-results{width:min(780px,calc(100% - 32px));margin:0 auto;padding:90px 0 80px}.nlm-result-hero{text-align:center;padding:20px 0 34px}.nlm-result-hero small{color:var(--nlm-muted)}.nlm-score{font-size:clamp(62px,12vw,94px);font-weight:750;letter-spacing:-.06em;margin:8px 0}.nlm-result-summary{color:var(--nlm-muted);font-size:15px}.nlm-result-actions{display:flex;justify-content:center;gap:8px;flex-wrap:wrap;margin-top:20px}.nlm-result-section{margin-top:28px}.nlm-result-section h3{font-size:15px;margin:0 0 12px}.nlm-mistakes{display:grid;gap:10px}.nlm-mistake{border:1px solid var(--nlm-line);border-radius:14px;background:var(--nlm-option);padding:17px}.nlm-mistake-top{display:flex;align-items:start;justify-content:space-between;gap:12px}.nlm-mistake-number{color:var(--nlm-red-text);font-size:11px;font-weight:750}.nlm-mistake-question{font-weight:650;line-height:1.45;margin-top:5px}.nlm-answer-row{margin-top:12px;font-size:13px;line-height:1.5}.nlm-answer-row b{display:block;color:var(--nlm-muted);font-size:10px;text-transform:uppercase;letter-spacing:.06em;margin-bottom:3px}.nlm-answer-row.wrong{color:var(--nlm-red-text)}.nlm-answer-row.correct{color:var(--nlm-green-text)}.nlm-review-q{margin-top:12px;border:0;background:transparent;color:var(--nlm-accent);font-weight:650;cursor:pointer;padding:0;font-size:12px}.nlm-perfect{border:1px solid var(--nlm-green);background:var(--nlm-green-bg);padding:18px;border-radius:14px;color:var(--nlm-green-text);line-height:1.5}
    @media(max-width:600px){#quiz-container{width:min(100% - 20px,760px);padding-top:76px}.q-text{font-size:17px!important;margin:0 8px 24px!important}.option{padding:16px 14px!important;grid-template-columns:29px minmax(0,1fr)!important;font-size:15px!important}.nlm-inline-feedback{font-size:14px}.nlm-footer-inner{width:calc(100% - 20px)}.nlm-review-link{display:none}.nlm-question-grid{grid-template-columns:repeat(4,1fr)}}
  `;
}
